model:
    path: "./best.pt"
    conf_threshold: 0.25 # <-- TURUNKAN (Agar model lebih berani menebak)
    img_size: 640 # <-- NAIKKAN ke 640 (Agar objek kecil terlihat jelas)

device:
    use_gpu: false
